<Tweet tweetId="1167024813359194112" options={{ theme: `dark` }} />
<Tweet tweetId="1167083952017956864" options={{ theme: `dark` }} />

 allMeetupGroup {
    edges {
      node {
        name
        urlname
        key_photo {
          photo_link
        }
        group_photo {
          highres_link
          photo_link
        }
      }
    }
  }

    query($regex: String) {
   allCloudinaryMedia(filter: {public_id: {regex: $regex}} ) {
    edges {
      node {
        txb_preview_image {
          url
        }
      }
    }
  }
  }

  
  allCloudinaryMedia(filter: {public_id: {regex: "/coding-berlin/"}}) {
    edges {
      node {
        resource_type
        type
        public_id
        format
        url
        internal {
          mediaType
        }
        txb_preview_image {
          secure_url
        }
        maxeco {
          secure_url
        }
        thumb_dims {
          w
          h
        }
      }
    }
    pageInfo {
      itemCount
      currentPage
      pageCount
      hasNextPage
      hasPreviousPage
    }
  }