[build]
  functions = "./lambda"
  publish = "public"

[dev]
  command = "npm run build"
  port = 3000 # Port that the dev server will be listening on
  targetPort = 3000 # Port of target app server
  publish = "public" # If you use a _redirect file, provide the path to your static content folder
  autoLaunch = true

[[redirects]]
  from = "/global_1"
  to = "/meetup/ck8vxvl1k1a700104ygm809n9"
  status = 301
  force = false
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/global_2"
  to = "/meetup/cka2ooxts00ly0109uvysepfk"
  status = 301
  force = false
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/global_3"
  to = "/meetup/ckal9jk2o1b9x01608ig10n4q"
  status = 301
  force = false
  headers = {X-From = "Netlify"}

[[plugins]]
  package = "netlify-plugin-gatsby-cache"